[package]
name = "amd_gfx_disasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitutils = "3.0.1"
num-traits = "0.2"
num-derive = "0.3"